defaultPulsarImageRepository: apachepulsar/pulsar
defaultPulsarImageTag: 4.0.8
defaultPullPolicy: IfNotPresent
initialize: false
useReleaseStatus: false
images:
  broker:
    repository: apachepulsar/pulsar
    tag: 4.0.8
    pullPolicy: IfNotPresent
labels:
  catalog.anaplan.io/component: pulsar
  catalog.anaplan.io/domain: persistence
  catalog.anaplan.io/owner: persistence
  catalog.anaplan.io/system: pulsar
components:
  zookeeper: true
  oxia: false
  bookkeeper: true
  autorecovery: true
  broker: true
  functions: true
  proxy: true
  toolset: true
  pulsar_manager: false
tls:
  enabled: true
  proxy:
    enabled: true
    dnsNames:
      - pulsar-1a-proxy.pulsar.svc.cluster.local
  broker:
    enabled: true
  bookie:
    enabled: true
  zookeeper:
    enabled: true
  function_instance:
    enabled: true
auth:
  authentication:
    enabled: true
    jwt:
      enabled: true
  authorization:
    enabled: true
  superUsers:
    broker: "broker-admin"
    proxy: "proxy-admin"
    client: "admin"
    manager: "admin"
  useProxyRoles: true
certs:
  internal_issuer:
    apiVersion: cert-manager.io/v1
    enabled: false
    component: internal-cert-issuer
    type: selfsigning
    duration: 2160h
    renewBefore: 360h
  issuers:
    ca:
      name: ca-issuer
      secretName: pulsar-1a-tls-zookeeper
      kind: ClusterIssuer
      group: cert-manager.io
zookeeper:
  replicaCount: 3
  gracePeriod: 360
  podMonitor:
    enabled: true
  restartPodsOnConfigMapChange: true
  topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - pulsar
      - key: release
        operator: In
        values:
        - pulsar
      - key: component
        operator: In
        values:
        - zookeeper
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1
    limits:
      memory: 512Mi
      cpu: 0.3
  volumes:
    useSeparateDiskForTxlog: false
    persistence: true
    data:
      name: data
      size: 5Gi
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx128m
    PULSAR_GC: >
      -XX:+UseZGC
      -XX:+ZGenerational
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:+ExitOnOutOfMemoryError
      -XX:+DisableExplicitGC
      -XX:+PerfDisableSharedMem
bookkeeper:
  gracePeriod: 360
  podMonitor:
    enabled: true
  replicaCount: 3
  restartPodsOnConfigMapChange: true
  topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - pulsar
      - key: release
        operator: In
        values:
        - pulsar
      - key: component
        operator: In
        values:
        - bookie
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  resources:
    requests:
      memory: 1Gi
      cpu: 0.5
    limits:
      memory: 1Gi
      cpu: 1.0
  volumes:
    persistence: true
    journal:
      name: journal
      size: 20Gi
    ledgers:
      name: ledgers
      size: 20Gi
  configData:
    PULSAR_MEM: >
      -Xms256m
      -Xmx256m
      -XX:MaxDirectMemorySize=256m
    PULSAR_GC: >
      -XX:+UseZGC
      -XX:+ZGenerational
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:+ExitOnOutOfMemoryError
      -XX:+DisableExplicitGC
      -XX:+PerfDisableSharedMem
    minorCompactionThreshold: "0.7"     # default 0.2 (use default)
    minorCompactionInterval: "360"      # default 3600 seconds (6 minutes vs default 1 hour)
    majorCompactionThreshold: "0.9"     # default 0.5
    majorCompactionInterval: "1140"    # default 86400 seconds (3 hours vs default 1 day)
    gcWaitTime: "300000"                # default 900000 milli-seconds (5 minutes vs default 15 minutes)
    isForceGCAllowWhenNoSpace: "true"   # default false
    diskUsageLwmThreshold: "0.85"   # default 0.90
    diskUsageWarnThreshold: "0.9"   # default 0.95
    diskUsageThreshold: "0.95"      # default 0.95 (use default)
    diskCheckInterval: "1800"       # default 10000
broker:
  gracePeriod: 360
  podMonitor:
    enabled: true
    interval: 20s
    scrapeTimeout: 18s
  component: broker
  replicaCount: 3
  restartPodsOnConfigMapChange: true
  topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - pulsar
      - key: release
        operator: In
        values:
        - pulsar
      - key: component
        operator: In
        values:
        - broker
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"    
  resources:
    requests:
      memory: 1Gi
      cpu: 0.5
    limits:
      memory: 1Gi
      cpu: 1.0
  configData:
    PULSAR_MEM: >
      -Xms256m -Xmx256m -XX:MaxDirectMemorySize=256m
    PULSAR_GC: >
      -XX:+UseZGC
      -XX:+ZGenerational
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:+ExitOnOutOfMemoryError
      -XX:+DisableExplicitGC
      -XX:+PerfDisableSharedMem
    managedLedgerDefaultEnsembleSize: "2"
    managedLedgerDefaultWriteQuorum: "2"
    managedLedgerDefaultAckQuorum: "2"
    forceDeleteTenantAllowed: "true"
    forceDeleteNamespaceAllowed: "true"
    tlsEnabled: "true"
    tlsAllowInsecureConnection: "true"
proxy:
  gracePeriod: 360
  podMonitor:
    enabled: true
    interval: 20s
    scrapeTimeout: 18s
  replicaCount: 3
  restartPodsOnConfigMapChange: true
  topologySpreadConstraints:
  - labelSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - pulsar
      - key: release
        operator: In
        values:
        - pulsar
      - key: component
        operator: In
        values:
        - proxy
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  annotations: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 0.2
    limits:
      memory: 512Mi
      cpu: 0.4
  configData:
    PULSAR_MEM: >
      -Xms128m -Xmx128m -XX:MaxDirectMemorySize=64m
    PULSAR_GC: >
      -XX:+UseZGC
      -XX:+ZGenerational
      -XX:+AlwaysPreTouch
      -XX:+UseTransparentHugePages
      -XX:+ExitOnOutOfMemoryError
      -XX:+DisableExplicitGC
      -XX:+PerfDisableSharedMem
    httpNumThreads: "16"
    authenticateMetricsEndpoint: "false"
  ingress:
    enabled: false
    annotations: {}
    ingressClassName: ""
    tls:
      enabled: true
      secretName: ""
    hostname: ""
    path: "/"
    pathType: ImplementationSpecific
toolset:
  gracePeriod: 5
  podMonitor:
    enabled: true
    interval: 20s
    scrapeTimeout: 18s
  component: toolset
  useProxy: true
  replicaCount: 1
  restartPodsOnConfigMapChange: false
  topologySpreadConstraints: []
  annotations: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1
    limits:
      memory: 512Mi
      cpu: 0.3
  configData:
    PULSAR_MEM: >
      -Xms256M
      -Xmx256M
      -XX:MaxDirectMemorySize=128M
autorecovery:
  replicaCount: 1
  gracePeriod: 360
  podMonitor:
    enabled: true
    interval: 20s
    scrapeTimeout: 18s
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1
    limits:
      memory: 512Mi
      cpu: 0.3
functions:
  gracePeriod: 360
  component: functions-worker
  useBookieAsStateStore: true
  rbac:
    limit_to_namespace: true
  service_account:
    annotations: {}

victoria-metrics-k8s-stack:
  enabled: false
  victoria-metrics-operator:
    enabled: false
    crds:
      plain: false
    operator:
      disable_prometheus_converter: true
  vmsingle:
    enabled: false
  vmagent:
    enabled: false
  vmalert:
    enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false